{!!Html::script('vendors/bower_components/jquery/dist/jquery.min.js')!!}
{!!Html::script('vendors/bower_components/bootstrap/dist/js/bootstrap.min.js')!!}
{!!Html::script('vendors/bower_components/salvattore/dist/salvattore.min.js')!!}
{!!Html::script('vendors/bower_components/flot/jquery.flot.js')!!}
{!!Html::script('vendors/bower_components/flot/jquery.flot.resize.js')!!}
{!!Html::script('vendors/bower_components/flot.curvedlines/curvedLines.js')!!}
{!!Html::script('vendors/sparklines/jquery.sparkline.min.js')!!}
{!!Html::script('vendors/bower_components/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js')!!}
{!!Html::script('vendors/bower_components/moment/min/moment.min.js')!!}
{!!Html::script('vendors/bower_components/fullcalendar/dist/fullcalendar.min.js')!!}
{!!Html::script('vendors/bower_components/simpleWeather/jquery.simpleWeather.min.js')!!}
{!!Html::script('vendors/bower_components/Waves/dist/waves.min.js')!!}
{!!Html::script('vendors/bootstrap-growl/bootstrap-growl.min.js')!!}
{!!Html::script('vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.min.js')!!}
{!!Html::script('vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js')!!}
{!!Html::script('js/flot-charts/curved-line-chart.js')!!}
{!!Html::script('js/flot-charts/bar-chart.js')!!}
{!!Html::script('js/charts.js')!!}
{!!Html::script('vendors/bootgrid/jquery.bootgrid.updated.min.js')!!}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
{!!Html::script('js/functions.js')!!}
{!!Html::script('js/actions.js')!!}
{!!Html::script('js/demo.js')!!}